name: Auto Merge Pull Request

on:
  pull_request:
    branches:
      - develop
      - qa
      - staging

jobs:
  merge-features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Merge Pull Request
        if: startsWith(github.head_ref, 'features/')
        uses: pascalgn/automerge-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: ${{ github.head_ref }}
          commit-message: 'Merge pull request ${GITHUB_SHA}'
          merge-method: 'merge'
