name: Auto Merge Pull Request

on:
  pull_request:
    branches:
      - develop
      - qa
      - staging

jobs:
  merge-features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3    

      - name: Check for feature branch
        id: check-branch
        run: |
          # Extract the branch name from the pull request head ref
          branch="${{ github.event.pull_request.head.ref }}"

          # Define the regular expression pattern to match the branch name
          pattern="^features/[A-Z0-9]+-[0-9]+/.*$"

          # Check if the branch name matches the pattern
          if [[ ! "$branch" =~ $pattern ]]; then
            echo "Pull request is not from a valid feature branch"
            exit 78 # Exit with a neutral status code to stop the job
          fi      

      - name: Merge feature branch to branch
        run: |
          # Extract the branch name from the pull request head ref
          branch="${{ github.event.pull_request.head.ref }}"

          # Merge the feature branch into the target branch
          git fetch
          git merge "$branch"
          git push origin "$GITHUB_REF"
