name: Build and deploy a branch

on:
  push:
    branches:
      - develop
      - qa
      - 'features/[A-Z0-9]+-[0-9]+/*'
      - staging
      - main
      - 'releases/*'

jobs:
  build-workflow:
    uses: ./.github/workflows/build-workflow.yml
    with:
      branch: ${{ github.event.ref }}
    concurrency:
      group: ${{ github.event.ref }}
      cancel-in-progress: true
