name: Code Analysis

on:
  push:
    branches:
      - 'features/[A-Z0-9]+-[0-9]+/*'

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Setup CodeQL
      uses: github/codeql-action/init@v2

    - name: Build and compile CodeQL database
      run: |
        dotnet build
        /opt/hostedtoolcache/CodeQL/*/bin/codeql database init --language=cs --source-root=. codeql-db

    - name: Perform code analysis
      uses: github/codeql-action/analyze@v2
      with:
        database: codeql-db
        query: security-extended.ql
        language: csharp
