name: "CodeAnalysis"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Perform Code Analysis
      uses: dotnet/code-analysis@v1
      id: code-analysis
      with:
        solution: MyTestWebApp.sln
        build-breaking: true
        security: 5.0-all
        performance: 5.0-all
        all-categories: 5.0-recommended
