name: Deploy to CI

on:
  push:
    branches: [ $branch ]
  pull_request:
    branches: [ $branch ]

env:
  branch: "develop"

jobs:
  build-workflow:
    uses: ./.github/workflows/build-workflow.yml
    with:
      branch: $branch
